### ISSUE TITLE
std::vector<bool> specialization

### ISSUE THREAD

**Issue by codecat062011** [niXman/yas#46] opened 2019-02-05 13:03 UTC
Hi, 

I´m playing around with Release 7.01 and I found that serialization/deserialization does not work for std::vector<bool> specialization.

Compilation error is 
.../types/concepts/array.hpp:66:26: error: lvalue required as unary & operand
and 
.../types/concepts/array.hpp:132:25: error: taking address of temporary

**Comment by niXman** [comment] 2019-02-05 13:09
Hi,

Hmm... Right, `vector<bool>` isnt vector.
I'll think about this... Thanks!

**Comment by niXman** [comment] 2019-02-05 17:24
Fixed in `master`: https://github.com/niXman/yas/commit/62ac0924f8ba91671b591647f9d5f5feed9c3b40

Closed.

**Closed** 2019-02-05 17:51 UTC

**Comment by cpp977** [comment] 2022-10-10 14:17
This specialization does not seem to work when using libc++.
The following code does not compile with libc++:
```
#include <vector>

#include "yas/serialize.hpp"
#include "yas/std_types.hpp"

int main()
{
    std::vector<bool> b = {false, true};
    constexpr std::size_t flags = yas::mem /*IO type*/ | yas::binary; /*IO format*/
    yas::shared_buffer b_buf = yas::save<flags>(b);
}
```
but it does compile with libstdc++.
For my tests I used clang 14.0.6 on arch linux.

**Comment by niXman** [comment] 2022-10-10 14:18
could you provide me an error report please?

**Comment by cpp977** [comment] 2022-10-10 14:20
It is a long template error:
```
/home/user/__LIBS__/yas/include/yas/binary_oarchive.hpp:84:16: error: implicit instantiation of undefined template 'yas::detail::serializer<yas::detail::type_prop::not_a_fundamental, yas::detail::ser_case::use_internal_serializer, 1, std::__bit_const_reference<std::vector<bool>>>'
        return serializer<
               ^
/home/user/__LIBS__/yas/include/yas/types/concepts/array.hpp:65:16: note: in instantiation of function template specialization 'yas::binary_oarchive<yas::mem_ostream, 1>::operator&<std::__bit_const_reference<std::vector<bool>>>' requested here
            ar & (*it);
               ^
/home/user/__LIBS__/yas/include/yas/types/std/vector.hpp:59:33: note: in instantiation of function template specialization 'yas::detail::concepts::array::save<1UL, yas::binary_oarchive<yas::mem_ostream, 1>, std::vector<bool>>' requested here
        return concepts::array::save<F>(ar, vector);
                                ^
/home/user/__LIBS__/yas/include/yas/binary_oarchive.hpp:89:12: note: in instantiation of function template specialization 'yas::detail::serializer<yas::detail::type_prop::not_a_fundamental, yas::detail::ser_case::use_internal_serializer, 1, std::vector<bool>>::save<yas::binary_oarchive<yas::mem_ostream, 1>>' requested here
        >::save(*this, v);
           ^
/home/user/__LIBS__/yas/include/yas/binary_oarchive.hpp:96:16: note: in instantiation of function template specialization 'yas::binary_oarchive<yas::mem_ostream, 1>::operator&<std::vector<bool>>' requested here
        return operator& (head).serialize(tail...);
               ^
/home/user/__LIBS__/yas/include/yas/binary_oarchive.hpp:101:16: note: in instantiation of function template specialization 'yas::binary_oarchive<yas::mem_ostream, 1>::serialize<std::vector<bool>>' requested here
        return serialize(args...);
               ^
/home/user/__LIBS__/yas/include/yas/serialize.hpp:63:5: note: in instantiation of function template specialization 'yas::binary_oarchive<yas::mem_ostream, 1>::operator()<std::vector<bool>>' requested here
    oa(std::forward<Types>(args)...);
    ^
serialization.cpp:107:37: note: in instantiation of function template specialization 'yas::save<257UL, std::vector<bool> &>' requested here
    yas::shared_buffer b_buf = yas::save<flags>(b);
                                    ^
/home/user/__LIBS__/yas/include/yas/detail/type_traits/type_traits.hpp:222:10: note: template is declared here
> struct serializer;
```

**Comment by cpp977** [comment] 2022-10-10 14:22
No problem and thanks for the quick reply!

**Comment by niXman** [comment] 2022-10-13 11:03
@cpp977 

hmm... can't reproduce.

```
clang++-14 -stdlib=libc++ -std=c++11 main.cpp -I yas/include -v
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
```

could you re-check please one more time?

**Comment by cpp977** [comment] 2022-10-13 11:15
A `git pull` actually solved the issue. Strange that it worked with libstdc++ but not libc++ with the version I had. But anyway, it is not an issue with the latest version of yas.
Thanks for checking it.

**Comment by niXman** [comment] 2022-10-13 11:20
np!
